### ISSUE TITLE
add BinHacken.github.io as repo link

### ISSUE THREAD

**Issue by H3wastooshort** [BinHacken/binhacken.github.io#1]
jus a suggestion

**Comment by spacehuhn** [comment]
Your suggestion is a bit unclear to me. 
BinHacken.github.io is the link to the github page hosted on this repository, that's how github pages work.
If you mean a link on the webpage that to link back to this repository, then OK I will add it.

**Comment by spacehuhn** [comment]
Anyhow, there's a link in the readme and a link on the website now.
